#include "../include/linux_target.h"
#include <stdio.h>
#include <stdlib.h>

void linux_generate_target(const char *filename, const char *code, int code_size, TargetType target_type) {
  FILE *f = fopen(filename, "wb");
  if (f) {
    fprintf(f, "; Generated by MiniCompiler\n");
    fprintf(f, ".intel_syntax noprefix\n");
    fprintf(f, ".section .text\n");

    if (target_type == TARGET_EXE) {
      fprintf(f, ".global main\n");
      fprintf(f, "main:\n");
    }
    else if (target_type == TARGET_SO) {
      fprintf(f, ".global _init\n");
      fprintf(f, "_init:\n");
    }

    fwrite(code, 1, code_size, f);

    if (target_type == TARGET_EXE) {
      fprintf(f, "mov rax, 60\n"); // exit syscall
      fprintf(f, "xor rdi, rdi\n");
      fprintf(f, "syscall\n");
    }
    else if (target_type == TARGET_SO) {
      fprintf(f, "ret\n");
    }

    fclose(f);
  }
}