#include "../include/win_target.h"
#include <stdio.h>
#include <stdlib.h>

// Simplified PE file header structures
#pragma pack(push, 1)
typedef struct {
  unsigned short e_magic;
  // ... other DOS header fields ...
} IMAGE_DOS_HEADER;

typedef struct {
  unsigned int signature;
  // ... other COFF header fields ...
} IMAGE_FILE_HEADER;
#pragma pack(pop)

void win_generate_target(const char *filename, const char *code, int code_size, TargetType target_type) {
  // In a real compiler, this would generate actual PE/COFF files
  // Here we just write the assembly code for demonstration

  FILE *f = fopen(filename, "wb");
  if (f) {
    fprintf(f, "; Generated by MiniCompiler\n");
    fprintf(f, ".386\n.model flat, stdcall\n");
    fprintf(f, "includelib minicrt.lib\n\n");

    if (target_type == TARGET_DLL) {
      fprintf(f, "LIBRARY %s\n", filename);
      fprintf(f, "EXPORTS\n");
      fprintf(f, "    DllMain @1\n");
    }

    fprintf(f, ".code\n\n");

    if (target_type == TARGET_EXE) {
      fprintf(f, "main PROC\n");
    }
    else if (target_type == TARGET_DLL) {
      fprintf(f, "DllMain PROC hInstance:DWORD, reason:DWORD, unused:DWORD\n");
    }

    fwrite(code, 1, code_size, f);

    if (target_type == TARGET_EXE) {
      fprintf(f, "ret\n");
      fprintf(f, "main ENDP\n");
    }
    else if (target_type == TARGET_DLL) {
      fprintf(f, "mov eax, 1\nret\n");
      fprintf(f, "DllMain ENDP\n");
    }

    fprintf(f, "END %s\n", target_type == TARGET_EXE ? "main" : "DllMain");
    fclose(f);
  }
}